# Introducción al análisis de Datos con python

## Funciones lambda
Una forma de escribir funciones que consisten en una única sentencia, el resultado de la cual es el valor devuelto.

In [7]:
#ordenar una colección de cadenas de texto por el número de las letras de que se compone cada cadena
strings = ["foo", "card", "bar", "aaaa", "abab"]
strings.sort(key=lambda x: len(set(x)))
strings

['aaaa', 'foo', 'abab', 'bar', 'card']

#### Generadores
Esto se lleva a cabo por medio del protocolo iterador, una forma genérica de hacer que los objetos sean iterables.

In [14]:
gen = (x ** 2 for x in range(100))
gen

<generator object <genexpr> at 0x71a42dd50380>

In [15]:
sum(gen)

328350

In [17]:
dict((x, x**2) for x in range(5))

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}

### Manejo de errores

In [18]:
def attemp_to_float(x):
    try:
        return float(x)
    except:
        return x
attemp_to_float('1')

1.0

In [19]:
attemp_to_float('someting')

'someting'

## Numpy

In [1]:
import numpy as np

In [3]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [4]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [5]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])